version: '3'

services:
  server:

    image: doobig/scpsl-docker:latest
    container_name: scpsl

    restart: unless-stopped
    stdin_open: true
    tty: true

    ports:
      - "7777:7777"

    environment:
      SCPSL_PORT: 7777

    volumes:
#      - steamcmd:/home/scpsl/.steamcmd
      - ./scpsl-data:/config/SCP Secret Laboratory

#volumes:
#  steamcmd: